# Default values for centNodeChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

centrifugeChainEndpoint: 'ws://localhost:9944'

fundingAccount: 'centrifugeAccount'

namespace: default

